### PR TITLE
Flake-Less compatibility

### PR DESCRIPTION
**Pull request by itzwam**
This PR lets anybody to import this repository without flakes enabled

keeping the flakes-enabled behavior unchanged

npins example:
``` 
  imports = [
    (import (import ./npins).NixVirt {
      inherit pkgs;
      inherit (pkgs) OVMFFull; # Change to inherit from an unstable version of pkgs
    }).nixosModules.default
  ];

```

### CODE REVIEW

**Comment by AshleyYakeley** [comment]
Would prefer to keep NixVirt flakes-only, rather than having to support the legacy way of doing things. You can import the flake in any case by using `builtins.getFlake`.

**Comment by Rosuavio** [comment]
"Flake-less" is not generally considered legacy amongst the community, or even the core nix project or anything based on it. I personally avoid flakes when it's easy enough too, and it's generally fairly easy to use niv or npins to avoid using flakes.

**Comment by Rosuavio** [comment]
"Flake-less" is not generally considered legacy amongst the community, or even the core nix project or anything based on it. I personally avoid flakes when it's easy enough too, and it's generally fairly easy to use niv or npins to avoid using flakes.

**Comment by Rosuavio** [comment]
This kind of change to simplify using a project without relying on flakes is fairly common amongst commonly used nix projects.

**Comment by itzwam** [comment]
This change allows anyone not depending on flakes to import the repo

builtins.getFlake is not available in flake-less world 😉

**Comment by AshleyYakeley** [comment]
OK, it's probably not fair to call the old unstructured way of doing things legacy while flakes is still marked as an experimental feature. Nevertheless at some point flakes will become stable, the `flakes` extension flag will go away and `builtins.getFlake` will always be available. This is the nix world I am interested in developing for, on my own time.

I can understand not wanting to use flakes for one's own stuff and using `getFlake` to work with other people's flakes, but I'm not interested in the additional maintenance burden to support people who won't even switch on the `flakes` extension. Flakes are coming anyway.

**Comment by itzwam** [comment]
k then 
let's fork

**Comment by AshleyYakeley** [comment]
See #61.

**Comment by AshleyYakeley** [comment]
Closing in favour of #61.

**Pull request closed without merging**
